### ISSUE TITLE
No check for Infinity

### ISSUE THREAD

**Issue by oguching** [lrlna/number-picker#1]
You are only checking if `input` is a number [here](https://github.com/lrlna/number-picker/blob/2e6e5fc616d5f4c9dd8cb2d3d83fd7bf84cc704a/index.js#L8). If it's `Infinity`, it still passes regex check and map can't do anything with Infinity.

You can do a check for finite numbers. @sindresorhus has a module [ is-finite](https://github.com/sindresorhus/is-finite) that can help

**Comment by lrlna** [comment]
hey! yea infinity check is a good one! I am hesitant to bring in another
package in here for something this small; doing a simple infinity check
will do though ✨

On Sun, 26 Mar 2017 at 22:38 oguchi nzekwe <notifications@github.com> wrote:

You are only checking if input is a number here
<https://github.com/lrlna/number-picker/blob/2e6e5fc616d5f4c9dd8cb2d3d83fd7bf84cc704a/index.js#L8>.
If it's Infinity, it still passes regex check and map can't do anything
with Infinity.

You can do a check for finite numbers. @sindresorhus
<https://github.com/sindresorhus> has a module is-finite
<https://github.com/sindresorhus/is-finite> that can help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lrlna/number-picker/issues/1>, or mute the thread

**Comment by lrlna** [comment]
`v1.0.1` :sparkles:
